import { useEffect, useState } from "react";

import { apiRequest } from "./lib/api";
import type {
  ConnectorAccount,
  PlannerResponse,
  StepRun,
  WorkflowRun,
  WorkflowSummary,
  WorkflowVersion,
} from "./lib/types";
import { ConnectorAccountsCard } from "./components/ConnectorAccountsCard";
import { PlannerCard } from "./components/PlannerCard";
import { RunTimelineCard } from "./components/RunTimelineCard";
import { SpecEditorCard } from "./components/SpecEditorCard";
import { WorkflowVersionsCard } from "./components/WorkflowVersionsCard";

const DEFAULT_PROMPT =
  "When a new client signs up, create a CRM entry and send a welcome email.";

function App() {
  const [specText, setSpecText] = useState(
    () => localStorage.getItem("wf_spec") ?? ""
  );
  const [workflowName, setWorkflowName] = useState(
    () => localStorage.getItem("wf_name") ?? "client-onboarding"
  );
  const [workflowDescription, setWorkflowDescription] = useState("Generated from prompt");
  const [sourcePrompt, setSourcePrompt] = useState(DEFAULT_PROMPT);

  const [workflows, setWorkflows] = useState<WorkflowSummary[]>([]);
  const [selectedWorkflowId, setSelectedWorkflowId] = useState<string>("");
  const [versions, setVersions] = useState<WorkflowVersion[]>([]);
  const [runs, setRuns] = useState<WorkflowRun[]>([]);
  const [selectedRunId, setSelectedRunId] = useState<string>("");
  const [runSteps, setRunSteps] = useState<StepRun[]>([]);
  const [connectors, setConnectors] = useState<ConnectorAccount[]>([]);

  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    void Promise.all([loadWorkflows(), loadRuns(), loadConnectors()]);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!selectedWorkflowId) return;
    void loadWorkflowVersions(selectedWorkflowId);
    void loadRuns(selectedWorkflowId);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedWorkflowId]);

  useEffect(() => {
    if (!selectedRunId) return;
    void loadRunSteps(selectedRunId);
  }, [selectedRunId]);

  useEffect(() => {
    localStorage.setItem("wf_spec", specText);
  }, [specText]);

  useEffect(() => {
    localStorage.setItem("wf_name", workflowName);
  }, [workflowName]);

  useEffect(() => {
    if (!message && !error) return;
    const timer = setTimeout(() => {
      setMessage("");
      setError("");
    }, 5000);
    return () => clearTimeout(timer);
  }, [message, error]);

  async function loadWorkflows() {
    const data = await apiRequest<WorkflowSummary[]>("/api/v1/workflows");
    setWorkflows(data);
    if (!selectedWorkflowId && data.length > 0) {
      setSelectedWorkflowId(data[0].id);
    }
  }

  async function loadWorkflowVersions(workflowId: string) {
    const data = await apiRequest<WorkflowVersion[]>(`/api/v1/workflows/${workflowId}/versions`);
    setVersions(data);
  }

  async function loadRuns(workflowId?: string) {
    const query = workflowId ? `?workflow_id=${workflowId}` : "";
    const data = await apiRequest<WorkflowRun[]>(`/api/v1/runs${query}`);
    setRuns(data);
    if (data.length > 0 && !selectedRunId) {
      setSelectedRunId(data[0].id);
    }
  }

  async function loadRunSteps(runId: string) {
    const data = await apiRequest<StepRun[]>(`/api/v1/runs/${runId}/steps`);
    setRunSteps(data);
  }

  async function loadConnectors() {
    const data = await apiRequest<ConnectorAccount[]>("/api/v1/connectors");
    setConnectors(data);
  }

  function handlePlannerResult(result: PlannerResponse, prompt: string) {
    setSourcePrompt(prompt);
    setSpecText(JSON.stringify(result.spec, null, 2));
    setWorkflowName(result.spec.name);
    setWorkflowDescription(`Generated by ${result.provider}`);
    setMessage("Workflow spec generated");
  }

  async function handleRunTriggered(runId: string) {
    await loadRuns(selectedWorkflowId || undefined);
    setSelectedRunId(runId);
    await loadRunSteps(runId);
  }

  async function processPendingSteps() {
    setBusy(true);
    setError("");
    setMessage("");
    try {
      await apiRequest<{ processed_steps: number }>("/api/v1/runs/process", { method: "POST" });
      await loadRuns(selectedWorkflowId || undefined);
      if (selectedRunId) await loadRunSteps(selectedRunId);
      setMessage("Pending steps processed");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unexpected error");
    } finally {
      setBusy(false);
    }
  }

  return (
    <main className="app-shell">
      <header className="topbar">
        <div>
          <p className="eyebrow">AI Business Process Automation Tool</p>
          <h1>Prompt to Workflow Runtime</h1>
        </div>
        <button onClick={() => void processPendingSteps()} disabled={busy}>
          Process Queue
        </button>
      </header>

      {(message || error) && (
        <section className={`notice ${error ? "error" : "ok"}`}>{error || message}</section>
      )}

      <section className="layout">
        <PlannerCard
          initialPrompt={DEFAULT_PROMPT}
          busy={busy}
          onGenerated={handlePlannerResult}
          onError={setError}
          onBusyChange={setBusy}
        />

        <SpecEditorCard
          busy={busy}
          specText={specText}
          onSpecTextChange={setSpecText}
          workflowName={workflowName}
          onWorkflowNameChange={setWorkflowName}
          workflowDescription={workflowDescription}
          onWorkflowDescriptionChange={setWorkflowDescription}
          selectedWorkflowId={selectedWorkflowId}
          sourcePrompt={sourcePrompt}
          onWorkflowCreated={loadWorkflows}
          onVersionCreated={() => loadWorkflowVersions(selectedWorkflowId)}
          onMessage={setMessage}
          onError={setError}
          onBusyChange={setBusy}
        />

        <WorkflowVersionsCard
          busy={busy}
          workflows={workflows}
          selectedWorkflowId={selectedWorkflowId}
          onSelectWorkflow={setSelectedWorkflowId}
          versions={versions}
          onVersionActivated={async () => {
            await loadWorkflowVersions(selectedWorkflowId);
            await loadWorkflows();
          }}
          onMessage={setMessage}
          onError={setError}
          onBusyChange={setBusy}
        />

        <RunTimelineCard
          busy={busy}
          selectedWorkflowId={selectedWorkflowId}
          runs={runs}
          selectedRunId={selectedRunId}
          runSteps={runSteps}
          onRunTriggered={handleRunTriggered}
          onRunSelected={(id) => setSelectedRunId(id)}
          onMessage={setMessage}
          onError={setError}
          onBusyChange={setBusy}
        />

        <ConnectorAccountsCard
          busy={busy}
          connectors={connectors}
          onConnectorSaved={loadConnectors}
          onMessage={setMessage}
          onError={setError}
          onBusyChange={setBusy}
        />
      </section>
    </main>
  );
}

export default App;
